---
label: Service
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: title
  label: title
- type: list
  name: categories
  label: categories
- type: text
  name: project_bg_color
  label: project_bg_color
- type: text
  name: project_fg_color
  label: project_fg_color
